### PR TITLE
Small breakout game.

### PR DESCRIPTION
**Pull request by egonelbre**

### CODE REVIEW

**Comment by jcoplien** [comment]
Looks good. Thanks for the Oval fix.

**Comment by ciscoheat** [comment]
Can we get some trig Math functions? :) I'm eager to test this by implementing some breakout-physics, like velocity changes depending on what part of the paddle you hit...!

**Comment by mbrowne** [comment]
Looks like you could add those by editing this file:
https://github.com/jcoplien/trygve/blob/master/src/main/java/info/fulloo/trygve/add_ons/MathClass.java

Of course, Cope may already be planning to add them or have a particular 
approach in mind for doing so.

**Comment by jcoplien** [comment]
Done. Sine, cosine, and atan2.

**Comment by ciscoheat** [comment]
Thank you! Time to dig up some forgotten math skills...

**Pull request merged**
