### PR TITLE
Deleted extraneous dir that fixes #17.

### LINKED ISSUE #17: Not compiling on Mac
After downloading the latest version just now, trygve is no longer compiling on my Mac. Initially it told me it needed recompilation so I deleted the contents of the `build` folder, and when that didn't work I tried cloning the repository to a new folder, but it still didn't compile -- see errors below. I'm running OS X 10.9.5.

Thanks

```
$ ./gradlew run
Incremental java compilation is an incubating feature.
:generateGrammarSource UP-TO-DATE
:compileJava
:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/mbrowne/dev/trygve2/src/main/generated/info/fulloo/trygve/parser/src/main/java/info/fulloo/trygve/parser/KantBaseListener.java:15: error: duplicate class: info.fulloo.trygve.parser.KantBaseListener
public class KantBaseListener implements KantListener {
       ^
/Users/mbrowne/dev/trygve2/src/main/generated/info/fulloo/trygve/parser/src/main/java/info/fulloo/trygve/parser/KantLexer.java:15: error: duplicate class: info.fulloo.trygve.parser.KantLexer
public class KantLexer extends Lexer {
       ^
/Users/mbrowne/dev/trygve2/src/main/generated/info/fulloo/trygve/parser/src/main/java/info/fulloo/trygve/parser/KantListener.java:11: error: duplicate class: info.fulloo.trygve.parser.KantListener
public interface KantListener extends ParseTreeListener {
       ^
/Users/mbrowne/dev/trygve2/src/main/generated/info/fulloo/trygve/parser/src/main/java/info/fulloo/trygve/parser/KantParser.java:15: error: duplicate class: info.fulloo.trygve.parser.KantParser
public class KantParser extends Parser {
       ^
4 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

### PR DESCRIPTION
**Pull request by ciscoheat**
You can reject this one if you've already fixed it in some other way.

### CODE REVIEW

**Comment by jcoplien** [comment]
Aargh. This keeps coming back like a bad penny. There’s some kind of conflict between the eclipse and gradle worlds. I can run antlr from eclipse but end getting the wrong version. I can run "gradlew antlr” and it ends in this crazy directory that I have to manually copy into src/main/generated/info/fulloo/trygve/parser/ https://github.com/jcoplien/trygve/pull/18/files#diff-0. I usually remember to delete this directory, but forgot this time.

Egon, I’ve not tried to fix this because I’m not very adept in this area and because I’m not conversant enough in the tools. For now, it’s an annoyance. Any deep insight into what’s going on?

— Cope

**Comment by egonelbre** [comment]
Wait, `gradlew antlr` generates it into the wrong directory?

In `build.gradle` there is this:

```
task antlr(type: Exec) {
    commandLine 'java',
        '-jar', './lib/antlr-4.5.1-complete.jar',
        '-o', 'src/main/generated/info/fulloo/trygve/parser',
        'src/main/java/info/fulloo/trygve/parser/Kant.g4'
} 
```

Which essentially means, run `java -jar ./lib/antlr-4.5.1-complete.jar -o src/main/generated/info/fulloo/trygve/parser src/main/java/info/fulloo/trygve/parser/Kant.g4` on the command line. When you run that directly from the command line, does it generate the code into the correct directory?

**Comment by jcoplien** [comment]
Copes-MacBook:info cope$ cd /Users/cope/Programs/Java/workspace/trygve
Copes-MacBook:trygve cope$ ls
LICENSE     build.gradle    lib     tests       trygve1.docx
README.md   gradle      settings.gradle trygve.iml
bin     gradlew     src     trygve.ipr
build       gradlew.bat target      trygve.iws
Copes-MacBook:trygve cope$ ls -l /Users/cope/Programs/Java/workspace/trygve/src/main/generated/info/fulloo/trygve/parser
total 472
-rw-r--r--+ 1 cope  staff    1147 26 Dec 22:55 Kant.tokens
-rw-r--r--+ 1 cope  staff   18944 26 Dec 22:55 KantBaseListener.java
-rw-r--r--+ 1 cope  staff   17453 26 Dec 22:55 KantLexer.java
-rw-r--r--+ 1 cope  staff    1147 26 Dec 22:55 KantLexer.tokens
-rw-r--r--+ 1 cope  staff   18610 26 Dec 22:55 KantListener.java
-rw-r--r--+ 1 cope  staff  168316 26 Dec 22:55 KantParser.java
Copes-MacBook:trygve cope$ java -jar ./lib/antlr-4.5.1-complete.jar -o src/main/generated/info/fulloo/trygve/parser src/main/java/info/fulloo/trygve/parser/Kant.g4
Copes-MacBook:trygve cope$ ls -l /Users/cope/Programs/Java/workspace/trygve/src/main/generated/info/fulloo/trygve/parser
total 472
-rw-r--r--+ 1 cope  staff    1147 26 Dec 22:55 Kant.tokens
-rw-r--r--+ 1 cope  staff   18944 26 Dec 22:55 KantBaseListener.java
-rw-r--r--+ 1 cope  staff   17453 26 Dec 22:55 KantLexer.java
-rw-r--r--+ 1 cope  staff    1147 26 Dec 22:55 KantLexer.tokens
-rw-r--r--+ 1 cope  staff   18610 26 Dec 22:55 KantListener.java
-rw-r--r--+ 1 cope  staff  168316 26 Dec 22:55 KantParser.java
drwxr-xr-x+ 3 cope  staff     102 27 Dec 16:54 src
Copes-MacBook:trygve cope$  ls -l /Users/cope/Programs/Java/workspace/trygve/src/main/generated/info/fulloo/trygve/parser/src/main/java/info/fulloo/trygve/parser
total 472
-rw-r--r--+ 1 cope  staff    1147 27 Dec 16:54 Kant.tokens
-rw-r--r--+ 1 cope  staff   18944 27 Dec 16:54 KantBaseListener.java
-rw-r--r--+ 1 cope  staff   17453 27 Dec 16:54 KantLexer.java
-rw-r--r--+ 1 cope  staff    1147 27 Dec 16:54 KantLexer.tokens
-rw-r--r--+ 1 cope  staff   18610 27 Dec 16:54 KantListener.java
-rw-r--r--+ 1 cope  staff  168316 27 Dec 16:54 KantParser.java
Copes-MacBook:trygve cope$

**Comment by egonelbre** [comment]
So much for things working the same across platforms. It seems that antlr doesn't handle paths consistently https://github.com/antlr/antlr4/issues/1087. I haven't yet figured out how to make gradle script work consistently.

**Comment by jcoplien** [comment]
> Den 27/12/2015 kl. 17.45 skrev Egon Elbre notifications@github.com:
> 
> So much for things working the same across platforms. It seems that antlr doesn't handle paths consistently antlr/antlr4#1087 https://github.com/antlr/antlr4/issues/1087. I haven't yet figured out how to make gradle script work consistently.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/jcoplien/trygve/pull/18#issuecomment-167425603.
> 
> O.K., just good to know.

Yes, this project has killed all of my idealism about portability… ;-(

**Comment by egonelbre** [comment]
It seems that the easiest way to achieve this is to keep the generated files in the same folder as .g4 file. i.e. `java -jar ./lib/antlr-4.5.1-complete.jar src/main/java/info/fulloo/trygve/parser/Kant.g4` will generate into the same folder as the `g4` file.  However this would smush together with the different passes, which would require separating the passes from `parser` package. i.e. either move Kant.g4 or move passes. I can do the necessary moves quite easily, if you pick one approach.

I actually don't blame ANTLR/Java; paths are annoying to work with across platforms. I blame Microsoft for not using the same path separator.

**Pull request merged**
