### PR TITLE
Fix Panel flickering

### PR DESCRIPTION
**Pull request by egonelbre**
These changes remove the Panel flickering, however some of the examples don't work quite right. (e.g. the borrow_library_panel examples). I'm not sure how to fix them. They looked broken before.

Also I made changes to the Panel API to make it reflect more how it does things internally, specifically:
- Removed `Panel.getForeground`, `Panel.setForeground`, `Panel.getBackground`, `Panel.setBackground` and replaced them with `Panel.getColor` and `Panel.setColor`.
- Removed `Panel.removeAll`, `Panel.remove` since they don't do anything anymore, things are rendered directly to a backbuffer.
- Similarly `Panel.drawString` doesn't return anything, because everything is rasterized immediately.
- Added `Panel.measureString` to make text positioning easier.

Calling `Panel.repaint` is now required to swap the front and backbuffer and `Panel.clear` is necessary to clear the previous image from backbuffer.

### CODE REVIEW

**Comment by jcoplien** [comment]
> Den 28/04/2016 kl. 19.48 skrev Egon Elbre <notifications@github.com <mailto:notifications@github.com>>:
> 
> These changes remove the Panel flickering, however some of the examples don't work quite right. (e.g. the borrow_library_panel examples). I'm not sure how to fix them. They looked broken before.

Something very likely broke in the (fragile) connection from the event handling logic (e.g., for reading an int from a Panel) and the refresh logic (all blocking reads issue a refresh before relinquishing the processor). This needs to be fixed. I can try to have a look at it but there are a number of things higher on my queue right now.

**Comment by egonelbre** [comment]
I'll see whether I can figure it out.

**Comment by jcoplien** [comment]
Thanks.

**Comment by egonelbre** [comment]
It was faster for me to rewrite the code than to try fix the previous ones. Anyways there now is a working example of it.

**Comment by jcoplien** [comment]
> Den 30/04/2016 kl. 15.56 skrev Egon Elbre notifications@github.com:
> 
> It was faster for me to rewrite the code than to try fix the previous ones. Anyways there now is a working example of it.

You mean the example? That’s fine.

**Comment by egonelbre** [comment]
The borrow library panel example I mean :). https://raw.githubusercontent.com/egonelbre/trygve/master/examples/borrow_library_panel5.k

2016-04-30 19_00_25-book checkout

Did you mean something else? BTW. I didn't notice any of the refreshing issues, just the colors got messed up.

**Comment by egonelbre** [comment]
And just now I realized what was wrong with the coloring, i.e. the fillRect previously didn't work, and hence it only drew an outline. After the fillRect fix it drew the background in the same color as the text.

**Comment by jcoplien** [comment]
Yeah, yeah, yeah, that’s what I figured, and that’s fine.

Maybe will get to the merge this evening.

**Comment by jcoplien** [comment]
I'll merge this now. I suspect there are some documentation updates that still need to be done and I'll look into those and do a bit more testing.

**Pull request merged**
