### PR TITLE
added -d option to compiler for compiling directories

### PR DESCRIPTION
**Pull request by mbrowne**

### CODE REVIEW

**Comment by jcoplien** [comment]
First, this seems odd as a compiler option — this is not a language feature, but rather one of the file system or operating system. I would rather separate out those concerns into code outside trygve.

Second, we need a broader vision of how to package multiple files together into a single entity. I suspect we will want some linguistic support to be able to name the directories and, à la Java, to include the folder name in the pathname of enclosed types. We don't do that on a file level now but probably should, and the idea should be extended to directories as it is in Java. (Type names are already hierarchical as in Java but currently take their path components solely from the scoping hierarchy. We need a more robust design.) Though the use of multiple -c options can lead to the same problem, the fix will be in the implementation of the file processing rather than in the usage options. I think the problems with -d go deeper and that the whole concept is an expedient that eventually will be supplanted.

Last, the feature needs more QA support. There are no supplied test cases or results. There should be a test case for each use case deviation (e.g., missing file, nested directory). There needs to be a design decision as to whether any single missing file will cause the Error empire to block ensuing execution. The directory-within-a-directory issue should either be properly dealt with or should issue an error message. There are already bugs in the current implementation which a casual code inspection can find: For example, it is trivial to create an exception if -d is the last parameter on the command line.

So it needs more work. I know it probably is a convenience to you and the way you are using the environment and I may ultimately merge in the pull request to make things easier for you, with the caveat that it may all be undone some day when we do this more fully right.

**Comment by mbrowne** [comment]
I had the impression that the concatenation of multiple files via 
specifying the -c option multiple times was a temporary solution, is 
that right? I was intending the -d option to likewise be a temporary 
solution, or at least one that should be significantly reworked later, 
with a convention to determine which file contains the main expression, 
proper linkage, etc.

But I do think it's a handy option to have in the meantime...so let's 
try to find a middle ground of making it a bit more robust while also 
not trying to perfect it 100% since it's not meant to be the final solution.

As to a test case, is there an existing test case for the -c option that 
I can follow (since this is fairly similar)? Should the test go in the 
same 'tests' folder as the other tests, or somewhere else?

**Comment by jcoplien** [comment]
> Den 06/03/2016 kl. 22.02 skrev Matt Browne notifications@github.com:
> 
>  had the impression that the concatenation of multiple files via 
> specifying the -c option multiple times was a temporary solution, is 
> that right?

Yes. It will either go away or, more likely, be reimplemented so that:
- there is parallel functionality in the GUI;
- line numbers are properly reported in error messages (currently, they are not)

> I was intending the -d option to likewise be a temporary 
> solution, or at least one that should be significantly reworked later, 
> with a convention to determine which file contains the main expression, 
> proper linkage, etc.

That’s why, in my remark, that I said I’d consider putting it in once it was debugged.

BTW, I put in -c largely in response to your requests to be able to compile multiple files…

> But I do think it's a handy option to have in the meantime...so let's 
> try to find a middle ground of making it a bit more robust while also 
> not trying to perfect it 100% since it's not meant to be the final solution.

That’s O.K. I also think that it should be removed from the usage print line, and that we should keep it as an undocumented feature.

I may do the same with the repeated -c. The line number errors are really annoying.

> As to a test case, is there an existing test case for the -c option that 
> I can follow (since this is fairly similar)? Should the test go in the 
> same 'tests' folder as the other tests, or somewhere else?

There is no meaningful way to run these tests from inside trygve so they’re not part of the distribution — I have my own Mac scripts here that test it. (Nice thing on the Mac is that you can execute jars directly…) For the time being I want to keep them out of the distribution.

**Comment by mbrowne** [comment]
I'm now wondering if the better approach might be to add support for 
compiling from standard input. Then I could compile and run a directory 
of source files like this:

cat example/*.k | trygve -r

And the standard input feature might be one we would want to keep, 
rather than being just a temporary solution. Also, the onus would be on 
the programmer to compile the files in the right order. What do you think?

**Comment by jcoplien** [comment]
I’m wary because I don’t know of any other compiler that does that. Part of the concern is relative path naming, I guess — if there is a #include in the file with a relative pathname, the compiler won’t know what directory the path is relative to… And eventually we may want the compiler to handle different kinds of files, distinguished by their suffix (analogous to the way that .i and .c and .C and .o files are all handled differently by the compiler). So just on precedent I want to avoid making it a “UN*X filter” …

**Comment by mbrowne** [comment]
Ok, I will focus on cleaning up the -d option as a temporary solution. I 
might not get to it for 2 weeks or so as I'm entering a busy period at 
work. I'm probably the person who cares most about this feature at the 
moment so I imagine there's no rush anyhow. Thanks.

**Comment by jcoplien** [comment]
BTW, another reason for not taking program source from standard input is that standard input also comes from standard input…. Imagine the use case of the spell-checking example: how would it work? You’d have to assign the trygve program’s input to the console, which may not be available, and in a way that may not be portable across Java platforms… No,  no, no… ;-)

**Pull request closed without merging**
